[tool.poetry]
name = "params-ai-api"
version = "0.1.0"
description = "API to enable Params.ai"
authors = ["Tosin Amuda <tosinamuda@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.104.0"
pydantic = "^2.4.2"
SQLAlchemy = "^2.0.22"
psycopg = {extras = ["binary"], version = "^3.1.12"}
llm-stack-kit = "^0.1.5"
uvicorn = {extras = ["standard"], version = "^0.23.2"}
chevron = "^0.14.0"

[tool.poetry.group.dev.dependencies]
black = "^23.10.0"
flake8 = "^6.1.0"
pylint = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
